package domain.common;

public enum TipServiciu {
    CONSULTATIE_GENERALA,
    CONSULTATIE_SPECIALIZATA,
    VACCINARE,
    INTERVENTIE_CHIRURGICALA,
    TRATAMENT,
    CONSULTATIE_URGENTA,
    CONTROL_POST_OPERATOR,
    CONSULTATIE_NUTRITIE,
    CONSULTATIE_COMPORTAMENTALA,
    DEPARAZITARE,
    CURATARE_DENTARA,
    MICROCIPARE
}

